import { SavedSessionItem } from '../types';
import { INITIAL_CAPTIONS, INITIAL_PARTICIPANTS } from './mockConversation';

export const INITIAL_SAVED_SESSIONS: SavedSessionItem[] = [
  {
    id: 'saved-1',
    sessionName: 'Architecture & Frontend Sync',
    date: 'Today, 10:25 AM',
    durationFormatted: '4m 12s',
    durationSeconds: 252,
    roomId: 'RT-482-910',
    speakerCount: 4,
    participants: [
      {
        id: 'user-elena',
        name: 'Elena Rostova',
        role: 'host',
        deviceType: 'Laptop',
        connectionState: 'connected',
        isMuted: false,
        isSpeaking: false,
        joinedAt: '10:20 AM',
        accentColor: '#0F172A',
      },
      ...INITIAL_PARTICIPANTS,
    ],
    captions: [
      ...INITIAL_CAPTIONS,
      {
        id: 'cap-h1',
        speakerId: 'user-alice',
        speakerName: 'Alice',
        text: 'The multi-device audio sync latency is staying consistently below 14ms across the room.',
        timestamp: '10:25 AM',
        deviceType: 'Laptop',
        accentColor: '#0D9488',
      },
      {
        id: 'cap-h2',
        speakerId: 'user-rahul',
        speakerName: 'Rahul',
        text: 'That gives our speaker diarization model plenty of headroom for clean attribution.',
        timestamp: '10:25 AM',
        deviceType: 'Phone',
        accentColor: '#2563EB',
      },
      {
        id: 'cap-h3',
        speakerId: 'user-priya',
        speakerName: 'Priya',
        text: 'The transcript flow looks crisp. Contrast and typography pass all legibility checks.',
        timestamp: '10:26 AM',
        deviceType: 'Tablet',
        accentColor: '#D97706',
      },
    ],
  },
  {
    id: 'saved-2',
    sessionName: 'Weekly Design System Review',
    date: 'Yesterday, 3:45 PM',
    durationFormatted: '12m 45s',
    durationSeconds: 765,
    roomId: 'RT-720-311',
    speakerCount: 3,
    participants: INITIAL_PARTICIPANTS,
    captions: [
      {
        id: 'ds-1',
        speakerId: 'user-priya',
        speakerName: 'Priya',
        text: 'We should ensure all form inputs maintain high-contrast focus rings and zero pills on static metadata.',
        timestamp: '3:46 PM',
        deviceType: 'Tablet',
        accentColor: '#D97706',
      },
      {
        id: 'ds-2',
        speakerId: 'user-alice',
        speakerName: 'Alice',
        text: 'Agreed. The desktop 100vh constraint works cleanly when the header and footer stay compact.',
        timestamp: '3:47 PM',
        deviceType: 'Laptop',
        accentColor: '#0D9488',
      },
      {
        id: 'ds-3',
        speakerId: 'user-rahul',
        speakerName: 'Rahul',
        text: 'I updated the color variables to match warm off-white #FAF9F6 and deep navy #0F172A.',
        timestamp: '3:49 PM',
        deviceType: 'Phone',
        accentColor: '#2563EB',
      },
    ],
  },
  {
    id: 'saved-3',
    sessionName: 'Q4 Spatial Audio Discovery',
    date: 'Oct 1, 11:15 AM',
    durationFormatted: '18m 30s',
    durationSeconds: 1110,
    roomId: 'RT-905-144',
    speakerCount: 4,
    participants: INITIAL_PARTICIPANTS,
    captions: [
      {
        id: 'sa-1',
        speakerId: 'user-alice',
        speakerName: 'Alice',
        text: 'Our test with three smartphones and one laptop proved that spatial triangulation beats single boundary mics.',
        timestamp: '11:16 AM',
        deviceType: 'Laptop',
        accentColor: '#0D9488',
      },
      {
        id: 'sa-2',
        speakerId: 'user-rahul',
        speakerName: 'Rahul',
        text: 'The packet loss recovery algorithms prevented any speech dropouts during the test.',
        timestamp: '11:18 AM',
        deviceType: 'Phone',
        accentColor: '#2563EB',
      },
    ],
  },
];
